from config.config import Config

config = Config(
    task="tsp",
    diffusion_type="categorical",
    learning_rate=0.0002,
    weight_decay=0.0001,
    lr_scheduler="cosine-decay",
    data_path="data",
    test_split="tsp/tsp50_test_concorde.txt",
    training_split="tsp/tsp50_train_concorde.txt",
    validation_split="tsp/tsp50_test_concorde.txt",
    models_path="models",
    ckpt_path="tsp/tsp50_categorical.ckpt",
    batch_size=32,
    num_epochs=50,
    diffusion_steps=2,
    validation_examples=8,
    diffusion_schedule="linear",
    inference_schedule="cosine",
    inference_diffusion_steps=50,
    device="cuda",
    sparse_factor=-1,
    n_layers=12,
    hidden_dim=256,
    aggregation="sum",
    use_activation_checkpoint=False,
    fp16=False,
)
